### ISSUE TITLE
How to change chinese language to english?

### ISSUE THREAD

**Issue by ThanhNguyen140797** [ycuwq/CalendarView#1]

**Comment by ycuwq** [comment]
Sorry, this is a calendar designed for Chinese users.
You can modify: `com.ycuwq.calendarview.utils.SolarUtil` and set `calendarView.setShowLunar(false);`

**Comment by ThanhNguyen140797** [comment]
> Sorry, this is a calendar designed for Chinese users.
> You can modify: `com.ycuwq.calendarview.utils.SolarUtil` and set `calendarView.setShowLunar(false);`

Thanks you. And another question: How to show (or where to modify) Month above the Week bar in CalendarView. Your CalendarView only has Week: Monday, Tuesday, Web....... and Day: 1 - 30 ( 31).
Sorry my bad english.

**Comment by ycuwq** [comment]
You can add a TextView above the CalendarView And set `calendarView.setOnPageSelectedListener`。
But this project is immature，I use it to learn custom view。
You have a better choice like [huanghaibin-dev/CalendarView](https://github.com/huanghaibin-dev/CalendarView)

**Comment by ThanhNguyen140797** [comment]
Thanks so much.

**Comment by ThanhNguyen140797** [comment]
Hello, can u help me fix this please? 
https://drive.google.com/open?id=1PAiI8np-orWzP7hqTJTGNWyGskCkzypy

**Comment by ycuwq** [comment]
Sorry，I didn't see the news before.
you shouldset RecyclerView BackgroundColor
